### ISSUE TITLE
Contact Form uses invalid link on Windows

### ISSUE THREAD

**Issue by JpzJr** [PasteBar/PasteBarApp#125]
In the Windows version of the app (I'm using 11), while in the About section, clicking on the @ attempts to open an invalid link: https://tauri.localhost/undefined/contact/?source=app&locale=en&dark=false
While recreating this error, I came across another error that may be linked: Open the "Help" menu in the menu bar, mouse over the "Support and Feedback" and click on the "Contact Us Form" gives a 404 error.

![image](https://github.com/user-attachments/assets/bce0cc19-f631-4bc7-8ad5-177cd3f07cc2)
![image](https://github.com/user-attachments/assets/b1906a18-6214-4a2c-a6f9-b903027a87ef)

Side note that is not related: I read in on of the tours that your multi-select is toggled by using the Alt key. Default for multi-select on Windows machines uses the Ctrl key. I was unable to find something to multi-select prior to filing this bug.

**Comment by kurdin** [comment]
@JpzJr  Thank you for report. I'll test it on Windows but on Mac. I can open Contact Us form without any error. 

Can you please test on Windows if this menu item opens contact form in modal ? 

<img width="1274" alt="image" src="https://github.com/user-attachments/assets/dbe9a9a9-36f1-44e7-a58e-54d0adede5e6">

<img width="1274" alt="image" src="https://github.com/user-attachments/assets/00c8b99d-6258-4d55-b835-e6dd02a57c1e">

>Side note that is not related: I read in on of the tours that your multi-select is toggled by using the Alt key. Default for multi-select on Windows machines uses the Ctrl key. I was unable to find something to multi-select prior to filing this bug.

I'll test it on Windows and let you know. Yes, I could messed up Alt with Ctrl because I am mostly use PasteBar on Mac. Thank you for reporting.

**Comment by kurdin** [comment]
@JpzJr I have 2 ways to multi select items in clipboard history. 

1. You can press `ALT + S` (Windows) to activate multi select or click menu item from history icon menu and use checkboxes to select multiple items in your history.
2. 
![image](https://github.com/user-attachments/assets/83d0151c-be3a-472e-a78b-ebfa414285de)

3. You can mouse hover a history item and press `CTRL + S` to select the item you currently have mouse on. This is what I usually do if I need to select a few items to drop to the board or delete. 

![image](https://github.com/user-attachments/assets/07517508-2459-4e01-bdac-9827f01ec97e)

**Comment by JpzJr** [comment]
Ok, I'm thinking Ctrl-Click when I multi-select. Ctrl-S and Alt-S work as explained here.

**Comment by kurdin** [comment]
> Ok, I'm thinking Ctrl-Click when I multi-select. Ctrl-S and Alt-S work as explained here.

Yeah, I think this is the right way to multi select `CTRL + item click` on Windows and `CMD + item click` on Mac. 

I'll add this on next update. Thanks!

**Comment by kurdin** [comment]
Bug overview: 

- The contact form link in the About section opens an invalid URL: https://tauri.localhost/undefined/contact/?source=app&locale=en&dark=false
- In the Help menu, clicking on "Contact Us Form" under "Support and Feedback" gives a 404 error
- This issue is specific to the Windows version of the app
- The contact form opens correctly on Mac

**Comment by kurdin** [comment]
Fixed in 
https://github.com/PasteBar/PasteBarApp/releases/tag/v0.6.0"
